import requests

from utils.animations import display_load_animation


def get_api_key() -> str:
    """
    Safely loads API key if it exists in environment variables.

    Returns:
        str: If API key fetch was successfull. Otherwise, returns None.
    """
    import os

    try:
        from dotenv import load_dotenv
        load_dotenv(".env")
    except ImportError:  # Silently skips if dotenv not installed
        pass

    API_KEY = os.getenv("API_KEY")

    if API_KEY is None:
        raise KeyError('The environment variable "API_KEY" was not found.')
    
    return API_KEY


def virustotal_available() -> bool:
    """
    Checks if user fulfills necessary criteria to use VirusTotal feature.

    Returns:
        bool: True, if an API key is provided in a ".env" file. Otherwise, False.
    """
    import os

    try:
        from dotenv import load_dotenv
        load_dotenv(".env")
    except ImportError:  # Silently skips if dotenv not installed
        pass

    API_KEY = os.getenv("API_KEY")
    
    return bool(API_KEY)
    

def submit_url_to_virustotal(target_url: str) -> str:
    """
    Submits a URL for scanning to VirusTotal and obtains the link with scan results.

    Args:
        target_url: The URL to be submitted to and scanned by VirusTotal.

    Returns:
        str: The link to the webpage with scan results generated by VirusTotal.
    """
    base_url = "https://www.virustotal.com/api/v3/urls"

    headers = {
        "x-apikey": get_api_key()
    }

    data = {
        "url": target_url
    }

    response = requests.post(base_url, headers=headers, data=data)
    data = response.json()
    scanned_url_link = data["data"]["links"]["self"]

    return scanned_url_link


def request_url_from_virustotal(target_url: str) -> dict:
    """
    Asks VirusTotal for a response concerning the scanned URL.

    Args:
        target_url: The link to the webpage with results of the previously scanned URL.

    Returns:
        dict: A dictionary object representing the malware statistics for a URL.
    """
    headers = {
        "x-apikey": get_api_key()
    }

    response = requests.get(target_url, headers=headers).json()
    stats = response["data"]["attributes"]["stats"]
    status = response["data"]["attributes"]["status"]

    return stats, status


def fetch_virustotal_stats(url: str) -> dict:
    """
    Pipeline for getting statistics on URL analysis by VirusTotal.

    Args:
        url: URL to be submitted to and scanned by VirusTotal.

    Returns:
        dict: A dictionary object representing the malware statistics for a URL.
    """
    import time

    analysis_url = submit_url_to_virustotal(url)

    # Ensures ~60 seconds of total delay time between retries: 10 + 20 + 30
    num_retries = 4
    delay_secs = 10

    # Polls VirusTotal analysis with increasing delays to allow scan completion
    for retry_counter in range(1, num_retries + 1):

        def attempt(retry_counter: int):
            stats, status = request_url_from_virustotal(analysis_url)

            # Returns complete and meaningful statistics
            if status == "completed" and any(stats.values()):
                print(end="\r", flush=True)  # Clears up INFO statement
                return stats
                        
            # Skip irrelevant sleep time for last attempt
            if retry_counter < num_retries:
                time.sleep(delay_secs * retry_counter)

            return None

        # Runs load animation for each attempt
        stats = display_load_animation(
            attempt,
            f"[INFO] Attempt {retry_counter}: Waiting for VirusTotal analysis to finish",
            retry_counter
        )

        if stats is not None:
            return stats

    return None
